[package]
name = "rustpython-compiler"
version = "0.1.0"
authors = ["RustPython Team"]
edition = "2018"

[dependencies]
rustpython-bytecode = { path = "../bytecode" }
rustpython-parser = { path = "../parser" }
num-complex = { version = "0.2", features = ["serde"] }
log = "0.3"
